runtime: nodejs14 # or another supported version
entrypoint: npm start

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 1
# use .env instead of env_variables because .env work on both local and production
